site_name: Chanel & Nicholas
theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: cyan
    accent: yellow
  favicon: '/static/images/favicon.png'
  icon:
    logo: material/home
  features:
    - navigation.instant
    - header.autohide
site_url: https://chanel.nicholaslyz.com/
nav:
  - Home: index.md
  - Trading Bot: trading-bot.md
  - Posts:
    - 27-29 Oct 2022 Bintan: posts/2022-09-15-bintan.md
    - 13-19 Nov 2022 Vietnam Camping: posts/2022-08-22-vietnam.md
    - 7-10 May 2022 France (Nice) Hiking: posts/2022-05-france-nice-hiking.md
    - 9-10 Apr 2022 Lazarus Camping: posts/2022-04-09-lazarus-camping.md
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - pymdownx.snippets
  - pymdownx.keys
plugins:
  - search