site_name: Chanel & Nicholas
theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: cyan
    accent: yellow
  favicon: '/static/images/favicon.png'
  icon:
    logo: material/home
  features:
    - navigation.instant
    - header.autohide
site_url: https://chanel.nicholaslyz.com/
nav:
  - Home: index.md
  - Stories:
    - The Story: stories/story.md
  - Posts:
    - Cooking Class Notes: posts/2023-05-14 Cooking class.md
    - Teas: posts/2023-02-19-teas.md
    - Shanmugan Video: posts/2022-12-28-shanmugan-transcript.md
    - Sweet Potatoes: posts/2023-02-06-sweet-potatoes.md
  - Trips:
    - "2023 Jun: Kamikochi, Japan": trips/2023-04-07-japan-hiking.md
    - "2022 Nov: Vietnam": trips/2022-08-22-vietnam.md
    - "2022 Oct: Bintan": trips/2022-09-15-bintan.md
    - "2022 May: Nice, France": trips/2022-05-france-nice-hiking.md
    - "2022 Apr: Lazarus Island": trips/2022-04-09-lazarus-camping.md
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - pymdownx.snippets
  - pymdownx.keys
plugins:
  - search