site_name: Chanel & Nicholas
site_url: https://chanel.nicholaslyz.com/

repo_name: extrange/chanel
repo_url: https://github.com/extrange/chanel/

theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: cyan
    accent: yellow
  favicon: "/static/images/favicon.png"
  icon:
    logo: material/home
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - header.autohide
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - toc.integrate

nav:
  - Blog:
      - blog/index.md
  - Stories:
      - stories/story.md
  - Trading Bot:
      - trading-bot/index.md
      - Introduction:
          - trading-bot/introduction/getting-started.md
          - trading-bot/introduction/env-variables.md
          - trading-bot/introduction/principles.md
          - trading-bot/introduction/architecture.md
      - Components:
          - trading-bot/components/trading-config.md
          - trading-bot/components/strategies-and-models.md
          - trading-bot/components/sizer.md
          - trading-bot/components/execution-engine.md
          - trading-bot/components/backtester.md
          - trading-bot/components/notebook.md
          - trading-bot/components/web-ui.md
      - Development:
          - trading-bot/development/asyncio.md
          - trading-bot/development/ibkr-connectivity.md
      - Guides:
          - trading-bot/guides/writing-model.md
          - trading-bot/guides/running-backtest.md
      - Trading Journal:
          - trading-bot/trading-journal/2023-07-21-chfjpy-cfd.md
          - trading-bot/trading-journal/2023-12-31-review.md
      - Notes:
          - trading-bot/notes/forex.md
          - trading-bot/notes/risk-management.md
          - trading-bot/notes/market-data.md
          - trading-bot/notes/useful-resources.md

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - pymdownx.snippets
  - pymdownx.keys

plugins:
  - search
  - glightbox
  - blog:
      blog_toc: true
      post_excerpt: required
      categories_allowed:
        - Trips
