[project]
name = "chanel"
version = "0.1.0"
description = "Chanel and Nicholas' Blog"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs-glightbox>=0.4.0",
    "mkdocs-material>=9.5.42",
]
